version: 2
updates:
  - package-ecosystem: "npm"  # Use "npm" for pnpm projects
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Ho_Chi_Minh"  # GMT+7 (Hanoi/Vietnam timezone)
      # time: "04:00"  # Time of day to check (UTC, format: "hh:mm")
      # day: "monday"  # Only for weekly schedule
      # timezone: "America/Los_Angeles"  # Timezone for schedule
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary

    # Only minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

    # # Additional optional configurations:

    # # Target branch (default is default branch)
    # target-branch: "main"

    # # Custom branch prefix for Dependabot PRs
    # pull-request-branch-name:
    #   separator: "/"  # or "-"

    # # Assignees and reviewers
    # assignees:
    #   - "username1"
    #   - "username2"

    # reviewers:
    #   - "phucbm"

    # # Team reviewers (for organizations)
    # reviewers:
    #   - "my-org/team-name"

    # # Labels to add to PRs
    # labels:
    #  - "dependencies"
    #  - "dependabot"

    # # Milestone to add to PRs
    # milestone: 4

    # # Commit message options
    # commit-message:
    #   prefix: "chore"  # Prefix for commit messages
    #   prefix-development: "chore"  # Prefix for dev dependencies
    #   include: "scope"  # Include package name in commit message

    # # Rebase strategy
    # rebase-strategy: "auto"  # "auto", "disabled"

    # # Allow Dependabot to update insecure dependencies
    # insecure-external-code-execution: "allow"  # "allow", "deny"

    # # Package manager specific options
    # vendor: true  # Vendor dependencies (go modules)

    # # Ignore specific dependencies
    # ignore:
    #   - dependency-name: "express"
    #   - dependency-name: "lodash"
    #     versions: ["4.x", "5.x"]  # Ignore specific versions
    #   - dependency-name: "@types/*"  # Wildcard patterns
    #     update-types: ["version-update:semver-patch"]

    # # Allow specific dependencies (overrides ignore rules)
    # allow:
    #   - dependency-name: "express"
    #   - dependency-type: "direct"  # "direct", "indirect", "all"
    #   - dependency-type: "development"  # "development", "production"

    # # Groups (combine multiple updates into single PR)
    # groups:
    #   production-dependencies:
    #     dependency-type: "production"
    #   development-dependencies:
    #     dependency-type: "development"
    #   # Or group by patterns
    #   react:
    #     patterns:
    #       - "react*"
    #       - "@types/react*"

    # # Security updates only
    # open-pull-requests-limit: 0  # Set to 0 and use security-updates-only
    # # Note: security-updates-only is deprecated, use ignore rules instead

    # # Registries (for private packages)
    # registries:
    #   - npm-private

# # Registry configurations (if using private registries)
# registries:
#   npm-private:
#     type: "npm-registry"
#     url: "https://npm.example.com"
#     username: "dependabot"
#     password: "${{secrets.NPM_TOKEN}}"
#   # Docker registry example
#   docker-private:
#     type: "docker-registry"
#     url: "registry.example.com"
#     username: "dependabot"
#     password: "${{secrets.DOCKER_TOKEN}}"
