name: Dependabot Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Enables manual trigger via GitHub web

permissions:
  contents: write  # To create tags and releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Release
        uses: phucbm/dependabot-release-action@v1 #https://github.com/marketplace/actions/dependabot-release-action
        with:
          version-bump: 'patch'  # Use manual input or default to patch
          default-branch: 'main'   # Set your default branch name