name: Dependabot Release

on:
  push:
    branches: [main]

permissions:
  contents: write  # To create tags and releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Release
        uses: phucbm/dependabot-release-action@v1
        with:
          version-bump: 'patch'  # Always patch for dependency updates